### ISSUE TITLE
Bundle Size Too Large - 12Mb

### ISSUE THREAD

**Issue by stephanoparaskeva** [wazo-platform/wazo-js-sdk#329]
### Steps
1) `npm i @wazo/sdk`
2) `cd node_modules`
3) `du -h @wazo/sdk`
> 12M

This is very large and I don't know how to get production minified+gzipped dist version. As I need the package to be less than 500kb.

Even just the Dist folder is 3.1Mb!
1) `npm i @wazo/sdk`
2) `cd node_modules`
3) `du -h @wazo/sdk/dist`
> 3.1M

**Comment by manuquentin** [comment]
Thanks @stephanoparaskeva for reporting this issue.
We'll investigate how we can reduce the bundle size, [here the dependencies we use and why the minified version weight 1.4mb](https://bundlephobia.com/scan-results?packages=sip.js@0.15.11,events@3.1.0,fstream@1.0.12,globby@11.0.0,google-libphonenumber@3.2.7,js-base64@2.5.2,jsrsasign@8.0.12,moment@2.24.0,node-fetch@2.6.0,reconnecting-websocket@4.4.0,sdp-transform@2.14.0,webrtc-adapter@7.5.1).

We'll see how to provide a bundle without :
 - google-libphonenumber: 531.9 kB
 - jsrsasign: 223.6 kB
 - moment: 231.7 kB
- globby: 74.8 kB

For now, you can use the file you need directly in your code, like :
`import WebRTCPhone from '@wazo/sdk/lib/domain/Phone/WebRTCPhone';`

**Comment by stephanoparaskeva** [comment]
> Thanks @stephanoparaskeva for reporting this issue.
> We'll investigate how we can reduce the bundle size, [here the dependencies we use and why the minified version weight 1.4mb](https://bundlephobia.com/scan-results?packages=sip.js@0.15.11,events@3.1.0,fstream@1.0.12,globby@11.0.0,google-libphonenumber@3.2.7,js-base64@2.5.2,jsrsasign@8.0.12,moment@2.24.0,node-fetch@2.6.0,reconnecting-websocket@4.4.0,sdp-transform@2.14.0,webrtc-adapter@7.5.1).
> 
> We'll see how to provide a bundle without :
> 
> * google-libphonenumber: 531.9 kB
> * jsrsasign: 223.6 kB
> * moment: 231.7 kB
> * globby: 74.8 kB
> 
> For now, you can use the file you need directly in your code, like :
> `import WebRTCPhone from '@wazo/sdk/lib/domain/Phone/WebRTCPhone';`

Thank you for the quick response. 
What do you recommend for React-Native peer-to-peer audio call and video call. Using CallKit.
I don't need phone calls, just 1-to-1 audio and 1-to-1 video as options. 

On top of this I've investigated react-native-webrtc that @wazo uses in the [example](https://github.com/wazo-platform/wazo-react-native-demo) and that seems to be:
> 72Mb

#### Steps
`npm i react-native-webrtc`
`cd node_modules`
`du -h react-native-webrtc`
> 72M

**Comment by manuquentin** [comment]
Hi @stephanoparaskeva,
We provides a lot of files with this SDK, like [esm files](https://github.com/wazo-platform/wazo-js-sdk/blob/master/rollup.config.js#L8), [commonJS files](https://github.com/wazo-platform/wazo-js-sdk/blob/master/rollup.config.js#L19)... 
The size of the project doesn't represent the size of your application.

You can make a diff on your `.apk` or `.ipa` file before and after adding the `wazo/sdk` to be able to really know the size added by the dependency.

To be able to make call, you'll need :
`import Wazo from '@wazo/sdk/lib/simple';`

You can check our [wazo-react-native-demo](https://github.com/wazo-platform/wazo-react-native-demo) repo

**Comment by stephanoparaskeva** [comment]
> Hi @stephanoparaskeva,
> We provides a lot of files with this SDK, like [esm files](https://github.com/wazo-platform/wazo-js-sdk/blob/master/rollup.config.js#L8), [commonJS files](https://github.com/wazo-platform/wazo-js-sdk/blob/master/rollup.config.js#L19) ... not all files will be used by your code.
> The size of the project doesn't represent the size of your application.
> 
> You can make a diff on your `.apk` or `.ipa` file before and after adding the `wazo/sdk` to be able to really know the size added by the dependency.
> 
> To be able to make call, you'll need :
> `import Wazo from '@wazo/sdk/lib/simple';`
> 
> You can check our [wazo-react-native-demo](https://github.com/wazo-platform/wazo-react-native-demo) repo

The readme doesn't describe how to start,
I am doing npm i npm start npx react-native run-ios and it fails

**Comment by manuquentin** [comment]
Thanks for the report. Can you open a bug with a description of the error in the [repository](https://github.com/wazo-platform/wazo-react-native-demo) ?

**Comment by stephanoparaskeva** [comment]
> Thanks for the report. Can you open a bug with a description of the error with logs in the [repository](https://github.com/wazo-platform/wazo-react-native-demo) please ?

I managed to get it up but I cannot connectio
<img width="394" alt="Screenshot 2020-06-22 at 14 30 22" src="https://user-images.githubusercontent.com/40718272/85293324-172a5b00-b495-11ea-8f2b-74c0604c40d6.png">


How do I authenticate?

**Comment by manuquentin** [comment]
To be able to login with wazo, you need a [wazo engine](https://wazo-platform.org/uc-doc/installation/install-system) configured.

**Comment by stephanoparaskeva** [comment]
> To be able to login with wazo, you need a [wazo engine](https://wazo-platform.org/uc-doc/installation/install-system) configured.

I see! That's amazing. 

Does this work for peer-to-peer voice/video (No phone numbers) 
I'm trying to create voice/video but not trying to create phonecalling. I want it to be like phonecalling but just over 4g/wifi?

**Comment by manuquentin** [comment]
Hello, Yes wazo's engine allow to make VoIP audio/video call via Internet using WebRTC.

**Comment by stephanoparaskeva** [comment]
> Hello, Yes wazo's engine allow to make VoIP audio/video call via Internet using WebRTC.

Ah, I see. It's brilliant.

Last question: How do I do the wazo-react-native-demo without using expo? I cannot use expo in my app and so how do i run demo without this, what will I miss? what do I need to installing??

**Comment by manuquentin** [comment]
There is no need to use expo with `wazo-react-native-demo`. It's an ejected expo app, so it's completely standalone now.

**Comment by stephanoparaskeva** [comment]
> There is no need to use expo with `wazo-react-native-demo`. It's an ejected expo app, so it's completely standalone now.

That's good, does it still need the expo libraries? is there any libraries I can uninstall if I only want VoIP audio/video?

**Comment by manuquentin** [comment]
Yes you can fork it and remove expo.

**Comment by stephanoparaskeva** [comment]
> Yes you can fork it and remove expo.

Can i just install the same packages in my own app and use app.js, dialer.js and launch and it will work? or did you do heavy configuration inside android/ios folders? and so I need to do a lot of work?
