### ISSUE TITLE
Endpoint chat `users/presences`

### ISSUE THREAD

**Issue by danymat** [wazo-platform/wazo-js-sdk#541]
Hello everyone, I want to use the endpoint:
```
api/chatd/1.0/users/presences
```

Is there a currently a way to retrieve the information with this sdk? 
If there isn't a function dedicated to it, does this sdk has a constructor/template for creating a request?

**Comment by danymat** [comment]
Thanks a lot! 
Subsidiary question: For this to work, I do need to know the uuids beforehand, is it so?

**Comment by manuquentin** [comment]
There is no way to fetch all contacts statuses in the SDK for now.
I'll add it in a future release.
