### ISSUE TITLE
Error on building website

### ISSUE THREAD

**Issue by danymat** [wazo-platform/wazo-js-sdk#545]
I'm using the SDK in order to create a website, but when building it and serving it, I get multiple errors in the builded file.

I'm using SDK version 0.35.6 and vitejs for building the website.

<img width="1436" alt="Capture d’écran 2021-05-24 à 17 45 24" src="https://user-images.githubusercontent.com/5306901/119372649-d431c280-bcb7-11eb-8cba-0e1c2a5ed6e5.png">

<img width="1097" alt="Capture d’écran 2021-05-24 à 17 46 58" src="https://user-images.githubusercontent.com/5306901/119372809-0b07d880-bcb8-11eb-9a6f-2f1130afd6d1.png">

Do you have an error in serving builded application with Wazo SDK in use? 

For some context:
- I use Vuejs with Vitejs for building the website. (the development server runs well)
- I do the imports like : `import { WazoWebSocketClient } from '@wazo/sdk'`

**Comment by sboily** [comment]
Hello, can you try with the SDK v0.32.45 please. I think we introduce an issue on 0.33 with node.js.

**Comment by danymat** [comment]
Hello, thanks for you help.

With 0.32.45 serving still fails, but with a different error:

<img width="1427" alt="Capture d’écran 2021-05-27 à 10 16 38" src="https://user-images.githubusercontent.com/5306901/119790923-a1b0e100-bed4-11eb-982f-c7aa59df5d0c.png">
<img width="1095" alt="Capture d’écran 2021-05-27 à 10 16 56" src="https://user-images.githubusercontent.com/5306901/119790956-abd2df80-bed4-11eb-96e2-d0bf7f09a955.png">

By the way the first issue linked to global being undefined I managed to solve it in latest version by using in `index.html`
```
<script type="text/javascript">
    window.global = window;
</script>
```

**Comment by manuquentin** [comment]
I've created https://github.com/wazo-platform/wazo-js-sdk-vitejs-example to show you how to use Wazo JS SDK with vitejs.
Can you tell me if you still have an issues with this example ?

Thanks !

**Comment by danymat** [comment]
Hello, 
On doing 
```bash
yarn build
yarn serve
```
It generates the same errors as me

**Comment by manuquentin** [comment]
Ok I've just tested with `yarn dev` without the rendering server-side.

It should be fixed in #548.
I've released a version `0.35.8-rc.2` and updated the https://github.com/wazo-platform/wazo-js-sdk-vitejs-example
Can you give it a try ?

Thanks !

**Comment by danymat** [comment]
It works well! 
Thank you

**Comment by danymat** [comment]
Ok so I think this fix did well for `build` and `serve`, but messed up `npm run dev`:

![Capture d’écran 2021-05-29 à 16 19 08](https://user-images.githubusercontent.com/5306901/120073662-99ee6980-c099-11eb-847b-b658e7462073.png)

I tried it one the example app and on my personal app, with the same output.

**Comment by manuquentin** [comment]
I've updated the demo with the `0.35.8-rc.5` version of the SDK. This should works not with `yarn serve` and `yarn buid`.

**Comment by danymat** [comment]
This new version reverted back to beginning:
- Yarn dev works 
- Yarn serve does not

**Comment by manuquentin** [comment]
I don't reproduce the issue on https://github.com/wazo-platform/wazo-js-sdk-vitejs-example with the `0.35.8-rc.5`.
What's your error ? Have you tried to `rm -rf node_modules && yarn install` ?

**Comment by danymat** [comment]
Oh yes sorry my bad!
It's now fixed, thank you for your support!
