### ISSUE TITLE
Error on webpack 5

### ISSUE THREAD

**Issue by BahmanBinary** [wazo-platform/wazo-js-sdk#685]
Hello everyone
I installed `@wazo/sdk` latest version (`0.39.0-beta.3`) on `create-react-app` latest version project that use webpack 5 and also I have an older CRA project that I install latest `@wazo/sdk` on that which use webpack 4 but I have many errors about export in first while in latter one all things is OK and I have no problem.
Of course webpack 5 is OK with `@wazo/sdk` version `0.38.x` and has no problem with it.

Error in terminal:
`Module not found: Error: Package path ./lib/simple is not exported from package .../node_modules/@wazo/sdk (see exports field in .../node_modules/@wazo/sdk/package.json)`

Error in browser:
`Uncaught Error: Cannot find module '@wazo/sdk/lib/simple'`

Thank you for your reply soon. 🙏🏼

**Comment by manuquentin** [comment]
Thanks @BahmanBinary we reproduced the issue.
We'll take a look.
